"use client";

import { useState } from "react";
import * as XLSX from "xlsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { upsertImportedProduct } from "@/lib/inventory/api";
import { parseCrossReferences } from "@/lib/codici/normalizeCode";
import { getReferenceGroups } from "@/lib/codici/storageReferences";

type Field = "internal_code" | "name" | "barcode" | "mav" | "cross" | "stock" | "minimum_stock" | "brand" | "category" | "location" | "supplier";
const labels: Record<Field, string> = { internal_code: "Codice interno", name: "Nome / descrizione", barcode: "Barcode", mav: "Codice MAV", cross: "Cross-reference", stock: "Giacenza iniziale", minimum_stock: "Scorta minima", brand: "Marca", category: "Categoria", location: "Ubicazione", supplier: "Fornitore" };
const fields = Object.keys(labels) as Field[];
const guess = (headers: string[], terms: string[]) => headers.find((header) => terms.some((term) => header.toUpperCase().includes(term))) ?? "";

export function InventoryImport() {
  const [headers, setHeaders] = useState<string[]>([]); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [mapping, setMapping] = useState<Record<Field, string>>({} as Record<Field, string>); const [priceHeaders, setPriceHeaders] = useState<string[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const selectFile = async (file?: File) => { if (!file) return; setError(""); try { const book = XLSX.read(await file.arrayBuffer(), { type: "array", raw: false }); const sheet = book.Sheets[book.SheetNames[0]]; const parsed = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "", raw: false }); const nextHeaders = Object.keys(parsed[0] ?? {}); if (!nextHeaders.length) throw new Error("Il foglio è vuoto o non contiene intestazioni."); setHeaders(nextHeaders); setRows(parsed); setPriceHeaders(nextHeaders.filter((header) => /prezzo|listino|price/i.test(header))); setMapping({ internal_code: guess(nextHeaders, ["CODICE INTERNO", "CODICE", "ARTICOLO"]), name: guess(nextHeaders, ["DESCRIZIONE", "NOME", "PRODOTTO"]), barcode: guess(nextHeaders, ["BARCODE", "EAN"]), mav: guess(nextHeaders, ["MAV"]), cross: guess(nextHeaders, ["CROSS", "REFERENCE"]), stock: guess(nextHeaders, ["GIACENZA", "QUANTIT"]), minimum_stock: guess(nextHeaders, ["SCORTA MINIMA", "MINIMO"]), brand: guess(nextHeaders, ["MARCA", "BRAND"]), category: guess(nextHeaders, ["CATEGORIA"]), location: guess(nextHeaders, ["UBICAZIONE", "SCAFFALE"]), supplier: guess(nextHeaders, ["FORNITORE"]) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile leggere il file."); } };
  const migrateLocalCodes = async () => { const groups = getReferenceGroups(); if (!groups.length) { setError("Non ci sono codici locali da migrare in questo browser."); return; } setLoading(true); setError(""); try { for (const group of groups) await upsertImportedProduct({ internal_code: group.nostroCodice || group.codiceMav || group.crossReferences[0], name: "", mav: group.codiceMav, crossReferences: group.crossReferences }, "Migrazione archivio locale"); setMessage(`Migrati ${groups.length} gruppi di codici locali. Completa nomi, prezzi e giacenze tramite Excel.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Migrazione interrotta."); } finally { setLoading(false); } };
  const runImport = async () => { const codeColumn = mapping.internal_code; if (!codeColumn) { setError("Scegli la colonna del codice interno prima di importare."); return; } setLoading(true); setError(""); let created = 0; let updated = 0; let skipped = 0; try { for (const row of rows) { const code = String(row[codeColumn] ?? "").trim(); if (!code) { skipped++; continue; } const prices = priceHeaders.map((header) => ({ name: header, amount: Number(String(row[header] ?? "").replace(",", ".")) })).filter((price) => Number.isFinite(price.amount)); const result = await upsertImportedProduct({ internal_code: code, name: mapping.name ? String(row[mapping.name] ?? "") : "", barcode: mapping.barcode ? String(row[mapping.barcode] ?? "") : "", mav: mapping.mav ? String(row[mapping.mav] ?? "") : "", crossReferences: mapping.cross ? parseCrossReferences(row[mapping.cross]) : [], stockQuantity: mapping.stock ? Number(String(row[mapping.stock] ?? "").replace(",", ".")) || 0 : 0, minimumStock: mapping.minimum_stock ? Number(String(row[mapping.minimum_stock] ?? "").replace(",", ".")) || null : null, brand: mapping.brand ? String(row[mapping.brand] ?? "") : "", category: mapping.category ? String(row[mapping.category] ?? "") : "", location: mapping.location ? String(row[mapping.location] ?? "") : "", supplier: mapping.supplier ? String(row[mapping.supplier] ?? "") : "", prices }); result.created ? created++ : updated++; } setMessage(`Importazione conclusa: ${created} nuovi prodotti, ${updated} aggiornati, ${skipped} righe senza codice ignorate.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Importazione interrotta."); } finally { setLoading(false); } };
  return <div className="space-y-5"><section className="rounded-xl border bg-card p-5"><label className="block text-sm font-semibold">File Excel<Input className="mt-3" type="file" accept=".xlsx,.xls" onChange={(e) => selectFile(e.target.files?.[0])} /></label><p className="mt-2 text-xs text-muted-foreground">Le colonne vengono lette dal primo foglio; puoi correggere la corrispondenza prima dell’importazione.</p></section><section className="rounded-xl border border-dashed bg-muted/20 p-5"><h2 className="font-semibold">Migra archivio precedente</h2><p className="mt-1 text-sm text-muted-foreground">Trasferisce i codici già salvati in questo browser. Non inventa nomi, prezzi o giacenze.</p><Button variant="outline" className="mt-3" onClick={migrateLocalCodes} disabled={loading}>Migra codici locali</Button></section>{headers.length > 0 && <><section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Mappa colonne</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field} className="text-sm font-medium">{labels[field]}<select className="mt-1.5 h-9 w-full rounded-md border bg-background px-3 text-sm" value={mapping[field] || ""} onChange={(e) => setMapping({ ...mapping, [field]: e.target.value })}><option value="">— Non presente —</option>{headers.map((header) => <option value={header} key={header}>{header}</option>)}</select></label>)}</div><p className="mt-4 text-xs text-muted-foreground">Le colonne con “prezzo” o “listino” nel nome vengono importate automaticamente come listini di vendita.</p></section><section className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Anteprima: {rows.length} righe trovate. La giacenza viene inizializzata solo per prodotti nuovi; i successivi import non la sovrascrivono.</p><Button className="mt-4" onClick={runImport} disabled={loading}>{loading ? "Importazione in corso…" : "Conferma importazione"}</Button></section></>}{message && <Alert><AlertDescription>{message}</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}</div>;
}
