"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { closeOrder, createOrder, findProductsByCode, getOrder, listOrders, scanProductIntoOrder, setOrderItemQuantity } from "@/lib/inventory/api";
import type { OrderDetail, OrderSummary, Product } from "@/types/inventory";
import { CheckCircle2, ClipboardList, Minus, Plus, ScanBarcode, X } from "lucide-react";

function totalQuantity(order: OrderSummary) { return order.order_items?.reduce((total, item) => total + item.quantity, 0) ?? 0; }

export function OrdersList() {
  const [orders, setOrders] = useState<OrderSummary[]>([]); const [name, setName] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [creating, setCreating] = useState(false);
  const reload = () => listOrders().then(setOrders).catch((cause) => setError(cause.message));
  useEffect(() => { reload(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; setCreating(true); try { const order = await createOrder(name, notes); window.location.assign(`/codici/ordini/${order.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile creare la lista."); } finally { setCreating(false); } };
  return <div className="space-y-6"><form onSubmit={submit} className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Nuova lista ordini</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Es. Ordine ricambi del 17 settembre" autoFocus /><Button disabled={creating || !name.trim()}><Plus className="mr-2 h-4 w-4" />Apri lista</Button></div><Textarea className="mt-3 min-h-12" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Note facoltative" /></form>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<div className="grid gap-3">{orders.map((order) => <Link key={order.id} href={`/codici/ordini/${order.id}`} className="rounded-xl border bg-card p-4 transition-colors hover:bg-muted/40"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-xs text-muted-foreground">#{order.order_number}</span><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${order.status === "open" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>{order.status === "open" ? "Aperta" : "Chiusa"}</span></div><h2 className="mt-1 font-semibold">{order.name}</h2><p className="mt-1 text-xs text-muted-foreground">Aggiornata {new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.updated_at))}</p></div><div className="text-right"><p className="text-lg font-bold tabular-nums">{totalQuantity(order)}</p><p className="text-xs text-muted-foreground">pezzi</p></div></div></Link>)}{orders.length === 0 && <div className="rounded-xl border border-dashed p-10 text-center"><ClipboardList className="mx-auto mb-3 h-8 w-8 text-muted-foreground" /><p className="font-medium">Nessuna lista ordine</p><p className="mt-1 text-sm text-muted-foreground">Apri la prima lista per iniziare a registrare le scansioni.</p></div>}</div></div>;
}

export function OrderWorkspace({ orderId }: { orderId: string }) {
  const router = useRouter(); const scanner = useRef<HTMLInputElement>(null); const [order, setOrder] = useState<OrderDetail | null>(null); const [value, setValue] = useState(""); const [matches, setMatches] = useState<Product[]>([]); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { setOrder(await getOrder(orderId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile caricare la lista."); } finally { setLoading(false); setTimeout(() => scanner.current?.focus(), 0); } };
  useEffect(() => { reload(); }, [orderId]);
  const add = async (product: Product) => { if (!order) return; setError(""); try { await scanProductIntoOrder(order.id, product.id); setNotice(`${product.name || product.internal_code} aggiunto alla lista.`); setMatches([]); setValue(""); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile aggiungere il prodotto."); } };
  const scan = async (event: React.FormEvent) => { event.preventDefault(); if (!value.trim() || !order) return; setNotice(""); setError(""); try { const found = await findProductsByCode(value); if (!found.length) { setError(`Nessun prodotto associato al codice ${value}.`); setValue(""); return; } if (found.length > 1) { setMatches(found); return; } await add(found[0]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Errore durante la scansione."); } finally { setTimeout(() => scanner.current?.focus(), 0); } };
  const changeQuantity = async (itemId: string, quantity: number) => { try { await setOrderItemQuantity(itemId, quantity); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile aggiornare la quantità."); } };
  const finish = async () => { if (!order || !confirm("Chiudere la lista? Dopo la chiusura sarà solo consultabile.")) return; try { await closeOrder(order.id); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossibile chiudere la lista."); } };
  if (loading && !order) return <p className="text-sm text-muted-foreground">Caricamento lista…</p>; if (!order) return <p className="text-sm text-destructive">{error || "Lista non trovata."}</p>;
  const open = order.status === "open"; const total = order.order_items.reduce((sum, item) => sum + item.quantity, 0);
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-sm text-muted-foreground">#{order.order_number}</span><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${open ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>{open ? "Lista aperta" : "Lista chiusa"}</span></div><h1 className="mt-1 text-2xl font-semibold">{order.name}</h1>{order.notes && <p className="mt-1 text-sm text-muted-foreground">{order.notes}</p>}</div>{open && <Button onClick={finish}><CheckCircle2 className="mr-2 h-4 w-4" />Chiudi lista</Button>}</div>
    {open && <form onSubmit={scan} className="rounded-xl border-2 border-primary/30 bg-card p-4"><label className="mb-2 flex items-center gap-2 text-sm font-semibold"><ScanBarcode className="h-4 w-4 text-primary" />Scansiona un prodotto</label><div className="flex gap-2"><Input ref={scanner} value={value} onChange={(e) => setValue(e.target.value)} placeholder="Punta qui la pistola barcode…" className="h-12 font-mono text-base" autoFocus /><Button className="h-12" disabled={!value.trim()}>Aggiungi</Button></div></form>}
    {notice && <Alert className="border-emerald-500/30 bg-emerald-500/5"><CheckCircle2 className="h-4 w-4 text-emerald-600" /><AlertDescription>{notice}</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    {matches.length > 0 && <section className="rounded-xl border border-amber-500/40 bg-amber-500/5 p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Scegli il prodotto corretto</h2><p className="text-sm text-muted-foreground">Questo codice è associato a più prodotti.</p></div><Button variant="ghost" size="icon" onClick={() => setMatches([])}><X className="h-4 w-4" /></Button></div><div className="mt-3 grid gap-2">{matches.map((product) => <Button key={product.id} variant="outline" className="h-auto justify-start py-3 text-left" onClick={() => add(product)}><span><span className="block font-mono text-xs text-muted-foreground">{product.internal_code}</span><span>{product.name || "Prodotto senza nome"}</span></span></Button>)}</div></section>}
    <section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">Prodotti nella lista</h2><span className="text-sm text-muted-foreground">{total} pezzi</span></div><div className="divide-y">{order.order_items.map((item) => <div key={item.id} className="flex items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><p className="font-mono text-xs text-muted-foreground">{item.internal_code_snapshot}</p><p className="truncate font-medium">{item.product_name_snapshot || "Prodotto senza nome"}</p>{item.product && <p className={`text-xs ${item.product.stock_quantity < 0 ? "text-destructive" : "text-muted-foreground"}`}>Giacenza: {item.product.stock_quantity} {item.product.unit}</p>}</div>{open ? <div className="flex items-center gap-2"><Button size="icon" variant="outline" className="h-9 w-9" onClick={() => changeQuantity(item.id, item.quantity - 1)}><Minus className="h-4 w-4" /></Button><span className="w-8 text-center font-bold tabular-nums">{item.quantity}</span><Button size="icon" variant="outline" className="h-9 w-9" onClick={() => changeQuantity(item.id, item.quantity + 1)}><Plus className="h-4 w-4" /></Button></div> : <span className="font-bold tabular-nums">× {item.quantity}</span>}</div>)}{order.order_items.length === 0 && <p className="px-4 py-10 text-center text-sm text-muted-foreground">{open ? "Scansiona il primo prodotto per aggiungerlo alla lista." : "Questa lista non contiene prodotti."}</p>}</div></section></div>;
}
